apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskservice
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: taskservice
  namespaceSelector:
    matchNames:
      - taskservice
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
